export type SVGIconKey =
	| 'responsive'
	| 'woodworking'
	| 'accessibility'
	| 'webDev'
	| 'photo'
	| 'react'
	| 'jquery'
	| 'angular'
	| 'svelte'
	| 'drupal'
	| 'figma'
	| 'sass'
	| 'docker'
	| 'typescript'
	| 'javascript'
	| 'html'
	| 'git'
	| 'unraid'
	| 'jira'
	| 'slack'
	| 'scrum'
	| 'diy'
	| 'play'
	| 'pause';

export const SVGIcons: Record<SVGIconKey, string> = {
	responsive: '/icons/responsive.svg',
	woodworking: '/icons/woodworking.svg',
	accessibility: '/icons/accessibility.svg',
	webDev: '/icons/webDev.svg',
	photo: '/icons/photo.svg',
	react: '/icons/react.svg',
	jquery: '/icons/jquery.svg',
	angular: '/icons/angular.svg',
	svelte: '/icons/svelte.svg',
	drupal: '/icons/drupal.svg',
	figma: '/icons/figma.svg',
	sass: '/icons/sass.svg',
	docker: '/icons/docker.svg',
	typescript: '/icons/typescript.svg',
	javascript: '/icons/javascript.svg',
	html: '/icons/html.svg',
	git: '/icons/git.svg',
	unraid: '/icons/unraid.svg',
	jira: '/icons/jira.svg',
	slack: '/icons/slack.svg',
	scrum: '/icons/scrum.svg',
	diy: '/icons/diy.svg',
	play: '/icons/play.svg',
	pause: '/icons/pause.svg'
};
